### ISSUE TITLE
jwt中间件使用后，/api/ping/ 接口 tps下降

### ISSUE THREAD

**Issue by FishGold** [hanguangbaihuo/sparrow_cloud_go#44]
![image](https://user-images.githubusercontent.com/16126683/97850929-a68f2700-1d2f-11eb-9d08-416651c737b5.png)

**Comment by waro163** [comment]
主要是由于log输出导致的性能下降。
生产环境中使用:
`app.Logger().SetLevel("info")`
或者使用默认log的level，iris默认log的level是info
